[{"message":"Cycle found in tasks (dependency graph): task-1 -> task-1","rule":"no-pipeline-task-cycle","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[113,119,120],"startLine":8,"startColumn":13,"endLine":8,"endColumn":19}},{"message":"Pipeline 'runafter-pipeline' references task 'my-task' but the referenced task cannot be found. To fix this, include all the task definitions to the lint task for this pipeline.","rule":"no-missing-resource","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[149,156,157],"startLine":10,"startColumn":15,"endLine":10,"endColumn":22}},{"message":"Pipeline 'runafter-pipeline' references task 'my-task' but the referenced task cannot be found. To fix this, include all the task definitions to the lint task for this pipeline.","rule":"no-missing-resource","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[230,237,238],"startLine":14,"startColumn":15,"endLine":14,"endColumn":22}},{"message":"Pipeline 'runafter-pipeline' references task 'my-task' but the referenced task cannot be found. To fix this, include all the task definitions to the lint task for this pipeline.","rule":"no-missing-resource","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[319,326,327],"startLine":18,"startColumn":15,"endLine":18,"endColumn":22}},{"message":"Pipeline 'runafter-pipeline' references task 'my-task' but the referenced task cannot be found. To fix this, include all the task definitions to the lint task for this pipeline.","rule":"no-missing-resource","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[400,407,408],"startLine":22,"startColumn":15,"endLine":22,"endColumn":22}},{"message":"Pipeline 'runafter-pipeline' uses task 'taks-2' (referenced as 'my-task'), and it depends on 'task-4', which doesn't exists (declared in runAfter)","rule":"no-pipeline-missing-task","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[263,269,269],"startLine":15,"startColumn":26,"endLine":15,"endColumn":32}},{"message":"Pipeline 'runafter-pipeline' uses task 'taks-3' (referenced as 'my-task'), and it depends on 'task-2', which doesn't exists (declared in runAfter)","rule":"no-pipeline-missing-task","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[343,351,352],"startLine":19,"startColumn":17,"endLine":19,"endColumn":25}},{"message":"Pipeline 'runafter-pipeline' uses task 'taks-4' (referenced as 'my-task'), and it depends on 'task-2', which doesn't exists (declared in runAfter)","rule":"no-pipeline-missing-task","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[424,446,447],"startLine":23,"startColumn":17,"endLine":23,"endColumn":39}},{"message":"Pipeline 'runafter-pipeline' uses task 'taks-4' (referenced as 'my-task'), and it depends on 'task-missing', which doesn't exists (declared in runAfter)","rule":"no-pipeline-missing-task","level":"error","path":"./regression-tests/general/run-after.yaml","loc":{"range":[433,445,445],"startLine":23,"startColumn":26,"endLine":23,"endColumn":38}}]